---
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Security/YAMLLoad:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6